name: ECIP Validation Workflow

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate the ECIP spec files
      run: bundle install && bundle exec ecip_validator _specs/*
