name: ECIP Validation Workflow

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Validate the ECIP spec files
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        shopt -s globstar; bundle exec ecip_validator _specs/**/*.md
